import type { Metadata } from "next";
import Link from "next/link";
import { ArrowIcon, Footer, Header } from "../components";
import { imageSet } from "../data";

export const metadata: Metadata = { title: "About Marbella For Sale", description: "Independent Marbella real estate advice, local knowledge and a personal service for international buyers and property owners." };

export default function AboutPage() {
  return <><Header /><main><section className="page-hero"><div className="shell"><p className="eyebrow">Marbella For Sale</p><h1>Local knowledge.<br /><em>International perspective.</em></h1><p>We are an independent real estate company based in Puerto Banús, helping clients navigate Marbella and the Costa del Sol with clarity and confidence.</p></div></section><section className="gallery" style={{ gridTemplateColumns: "1fr", gridTemplateRows: "680px", padding: 0 }}><figure style={{ gridArea: "auto" }}><img src={imageSet.marina} alt="Puerto Banús marina, Marbella" /></figure></section><section className="area-copy section shell"><div><p className="eyebrow">Our point of view</p><p className="lead">Luxury is not a price point. It is how carefully the entire experience is handled.</p></div><div className="body-copy"><p>Our role is to reduce noise and improve decisions. We listen before we search, inspect before we recommend, and give every client the same direct, personal attention — whether they are buying a first Marbella apartment or selling a significant private estate.</p><p>With access to the wider Costa del Sol market, we are not limited to our own listings. That independence allows us to stay focused on the right outcome for each client.</p><Link className="text-link" href="/contact">Meet us in Puerto Banús <ArrowIcon /></Link></div></section><section className="section" style={{ background: "var(--cream)" }}><div className="shell"><div className="section-heading"><p className="eyebrow">What guides us</p><h2>Quiet standards.<br /><em>Consistently applied.</em></h2></div><div className="editorial-grid"><article className="editorial-card"><span className="index">01</span><h2>Judgement</h2><p>We recommend selectively and explain the reasoning behind every recommendation.</p></article><article className="editorial-card"><span className="index">02</span><h2>Discretion</h2><p>Private requirements, off-market opportunities and negotiations are handled with care.</p></article><article className="editorial-card"><span className="index">03</span><h2>Continuity</h2><p>One accountable advisor stays close from the first brief through completion and beyond.</p></article></div></div></section></main><Footer /></>;
}
